In [1]:
import numpy as np
import pandas as pd
import matplotlib. pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('/content/titanic.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:

df.shape

(891, 12)

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:

from sklearn.impute import SimpleImputer
imp=SimpleImputer(strategy='median')

In [9]:

df['Age']=imp.fit_transform(df[['Age']])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [10]:

df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Embarked']=le.fit_transform(df['Embarked'])
df['Name']=le.fit_transform(df['Name'])
df['Sex']=le.fit_transform(df['Sex'])
df['Ticket']=le.fit_transform(df['Ticket'])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22.0,1,0,523,7.2500,NaN,2
1,2,1,1,190,0,38.0,1,0,596,71.2833,C85,0
2,3,1,3,353,0,26.0,0,0,669,7.9250,NaN,2
3,4,1,1,272,0,35.0,1,0,49,53.1000,C123,2
4,5,0,3,15,1,35.0,0,0,472,8.0500,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,548,1,27.0,0,0,101,13.0000,NaN,2
887,888,1,1,303,0,19.0,0,0,14,30.0000,B42,2
888,889,0,3,413,0,28.0,1,2,675,23.4500,NaN,2
889,890,1,1,81,1,26.0,0,0,8,30.0000,C148,0
890,891,0,3,220,1,32.0,0,0,466,7.7500,NaN,1

In [12]:

df['Embarked']=imp.fit_transform(df[['Embarked']])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22.0,1,0,523,7.2500,NaN,2.0
1,2,1,1,190,0,38.0,1,0,596,71.2833,C85,0.0
2,3,1,3,353,0,26.0,0,0,669,7.9250,NaN,2.0
3,4,1,1,272,0,35.0,1,0,49,53.1000,C123,2.0
4,5,0,3,15,1,35.0,0,0,472,8.0500,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,548,1,27.0,0,0,101,13.0000,NaN,2.0
887,888,1,1,303,0,19.0,0,0,14,30.0000,B42,2.0
888,889,0,3,413,0,28.0,1,2,675,23.4500,NaN,2.0
889,890,1,1,81,1,26.0,0,0,8,30.0000,C148,0.0
890,891,0,3,220,1,32.0,0,0,466,7.7500,NaN,1.0

In [13]:
df=df.drop('Cabin',axis=1)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,108,1,22.0,1,0,523,7.2500,2.0
1,2,1,1,190,0,38.0,1,0,596,71.2833,0.0
2,3,1,3,353,0,26.0,0,0,669,7.9250,2.0
3,4,1,1,272,0,35.0,1,0,49,53.1000,2.0
4,5,0,3,15,1,35.0,0,0,472,8.0500,2.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,548,1,27.0,0,0,101,13.0000,2.0
887,888,1,1,303,0,19.0,0,0,14,30.0000,2.0
888,889,0,3,413,0,28.0,1,2,675,23.4500,2.0
889,890,1,1,81,1,26.0,0,0,8,30.0000,0.0
890,891,0,3,220,1,32.0,0,0,466,7.7500,1.0

In [14]:

from scipy.stats import zscore
z_scores=zscore(df['Fare'])
df[np.abs(z_scores)>3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
27,28,0,1,260,1,19.0,3,2,95,263.0000,2.0
88,89,1,1,259,0,23.0,3,2,95,263.0000,2.0
118,119,0,1,70,1,24.0,0,1,585,247.5208,0.0
258,259,1,1,844,0,35.0,0,0,608,512.3292,0.0
299,300,1,1,71,0,50.0,0,1,585,247.5208,0.0
311,312,1,1,710,0,18.0,2,2,602,262.3750,0.0
341,342,1,1,258,0,24.0,3,2,95,263.0000,2.0
377,378,0,1,862,1,27.0,0,2,27,211.5000,0.0
380,381,1,1,86,0,42.0,0,0,610,227.5250,0.0
438,439,0,1,261,1,64.0,1,4,95,263.0000,2.0
527,528,0,1,245,1,28.0,0,0,583,221.7792,2.0
557,558,0,1,693,1,28.0,0,0,610,227.5250,0.0
679,680,1,1,137,1,36.0,0,1,608,512.3292,0.0
689,690,1,1,498,0,15.0,0,1,141,211.3375,2.0
700,701,1,1,45,0,18.0,1,0,610,227.5250,0.0
716,717,1,1,241,0,38.0,0,0,610,227.5250,0.0
730,731,1,1,14,0,29.0,0,0,141,211.3375,2.0
737,738,1,1,476,1,35.0,0,0,608,512.3292,0.0
742,743,1,1,711,0,21.0,2,2,602,262.3750,0.0
779,780,1,1,694,0,43.0,0,1,141,211.3375,2.0

In [15]:

from scipy.stats.mstats import winsorize as win
df['Fare']=win(df['Fare'],limits=[0.05,0.05])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,108,1,22.0,1,0,523,7.2500,2.0
1,2,1,1,190,0,38.0,1,0,596,71.2833,0.0
2,3,1,3,353,0,26.0,0,0,669,7.9250,2.0
3,4,1,1,272,0,35.0,1,0,49,53.1000,2.0
4,5,0,3,15,1,35.0,0,0,472,8.0500,2.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,548,1,27.0,0,0,101,13.0000,2.0
887,888,1,1,303,0,19.0,0,0,14,30.0000,2.0
888,889,0,3,413,0,28.0,1,2,675,23.4500,2.0
889,890,1,1,81,1,26.0,0,0,8,30.0000,0.0
890,891,0,3,220,1,32.0,0,0,466,7.7500,1.0

In [16]:

X = df[['PassengerId','Pclass', 'Sex', 'Age', 'Fare', 'SibSp', 'Parch', 'Embarked']]
y = df['Survived']

In [17]:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [18]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [20]:
y_pred = knn.predict(X_test)

In [21]:

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.83      0.89      0.86       105
           1       0.82      0.74      0.78        74

    accuracy                           0.83       179
   macro avg       0.83      0.81      0.82       179
weighted avg       0.83      0.83      0.83       179